{% set name = "cuda-nvtx" %}
{% set version = "13.4.49" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win64]
{% set target_name = "arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvtx/{{ platform }}/cuda_nvtx-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 66569def5423d3a9fd5b48ddd7621c345d26d2a2fe162b27162e8df4b4f036ec  # [linux64]
  sha256: f837ae94e9a24de805b45610340c3dbaf2058c874a2e201dd8b63712d32944c4  # [aarch64]
  sha256: 01a6f60403d79459f0b1ba00e3038e1ebdeaa0c8144751b9eb6245ab36c994c1  # [win64]
  sha256: 04e8d04a2656bc8ea14f3dec55a0173f0cd094f535bdcd8b4032d270afdd1625  # [win and arm64]

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0  # [linux]

outputs:
  - name: cuda-nvtx
    build:
      binary_relocation: false
      skip: true  # [not linux]
    files:
      - lib/libnv*.so.*                       # [linux]
      - targets/{{ target_name }}/lib/*.so.*  # [linux]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}  # [linux]
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - patchelf <0.18.0  # [linux]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libnvtx3interop.so.1                                # [linux]
        - test -L $PREFIX/lib/libnvtx3interop.so.1.1.0                            # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvtx3interop.so.1      # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvtx3interop.so.1.1.0  # [linux]
        - bash test-rpath.sh                                                      # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: A C-based API for annotating events, code ranges, and resources
      description: |
        A C-based API for annotating events, code ranges, and resources in your
        applications. Applications which integrate NVTX can use the Visual Profiler
        to capture and visualize these events and ranges.
      doc_url: https://docs.nvidia.com/nvtx/

  - name: cuda-nvtx-dev
    build:
      run_exports:   # [linux]
        - {{ pin_subpackage("cuda-nvtx", max_pin='x') }}  # [linux]
    files:
      - lib/libnv*.so                                    # [linux]
      - targets/{{ target_name }}/lib/*.so               # [linux]
      - targets/{{ target_name }}/include/nvtx3          # [linux]
      - Library\include\targets\{{ target_name }}        # [win]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-nvtx", exact=True) }}  # [linux]
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -L $PREFIX/lib/libnvtx3interop.so                                                      # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvtx3/nvToolsExtCuda.h                    # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvtx3interop.so                            # [linux]
        - if not exist %LIBRARY_INC%\targets\{{ target_name }}\nvtx3\nvToolsExt.h exit 1  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: A C-based API for annotating events, code ranges, and resources
      description: |
        A C-based API for annotating events, code ranges, and resources in your
        applications. Applications which integrate NVTX can use the Visual Profiler
        to capture and visualize these events and ranges.
      doc_url: https://docs.nvidia.com/nvtx/

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A C-based API for annotating events, code ranges, and resources
  description: |
    A C-based API for annotating events, code ranges, and resources in your
    applications. Applications which integrate NVTX can use the Visual Profiler
    to capture and visualize these events and ranges.
  doc_url: https://docs.nvidia.com/nvtx/

extra:
  feedstock-name: cuda-nvtx
  recipe-maintainers:
    - conda-forge/cuda
